-- Use to adjust size
WINDOW_MULITPLIER = .95

-- size of our actual window
WINDOW_WIDTH = 1280 * WINDOW_MULITPLIER
WINDOW_HEIGHT = 720 * WINDOW_MULITPLIER

-- size we're trying to emulate with push
VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 288

BACKGROUND_SCROLL_SPEED = 30
GROUND_SCROLL_SPEED = 60

BACKGROUND_LOOPING_POINT = 413